name: CI

on: 
  push:
    branches:
      - main

jobs:
  build:

    runs-on: macOS-10.15
    
    steps:
    - uses: actions/checkout@master
    - name: Start xcodebuild test
      run: xcodebuild -project GreenPanda.xcodeproj -scheme GreenPanda -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11,OS=13.7" test
