name: CI

on: 
  push:
    branches:
      - main

jobs:
  build:

    runs-on: macos-11
    
    steps:
    - name: Checkout codebase
      id: checkout
      uses: actions/checkout@master
        
    - name: Start xcodebuild test
      id: xcodebuild
      run: /Applications/Xcode_13.2.app/Contents/Developer/usr/bin/xcodebuild -project GreenPanda.xcodeproj -scheme GreenPanda -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11,OS=15.2" clean test

    - name: Archive production artifacts
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: failure_archive
        path: .
